### ISSUE TITLE
Failing on CentOS8

### ISSUE THREAD

**Issue by djgalloway** [sebastian-philipp/registries-conf-ctl#4]
I'm not sure why this is happening but `registries-conf-ctl` is failing on CentOS8.

```
[dgalloway@braggi10 ~]$ sudo /usr/local/bin/registries-conf-ctl add-mirror docker.io docker-mirror.front.sepia.ceph.com:5000
Traceback (most recent call last):
  File "/usr/local/bin/registries-conf-ctl", line 11, in <module>
    load_entry_point('registries-conf-ctl==1.0', 'console_scripts', 'registries-conf-ctl')()
  File "/usr/local/lib/python3.6/site-packages/registries_conf_ctl/cli.py", line 183, in main
    'Failed to read any file')
  File "/usr/local/lib/python3.6/site-packages/registries_conf_ctl/cli.py", line 144, in _raise_if_all_fail
    raise ValueError('{what}: {e}'.format(what=what,e=e))
ValueError: Failed to read any file: [Errno 2] No such file or directory: '/etc/docker/daemon.json'


[dgalloway@braggi10 ~]$ grep -v '^#' /etc/containers/registries.conf
unqualified-search-registries = ["registry.fedoraproject.org", "registry.access.redhat.com", "registry.centos.org", "docker.io"]
```

**Comment by djgalloway** [comment]
Probably because of:

```
[root@braggi10 ~]# /usr/local/bin/registries-conf-ctl add-mirror --conf=/etc/containers/registries.conf docker.io docker-mirror.front.sepia.ceph.com:5000
Traceback (most recent call last):
  File "/usr/local/bin/registries-conf-ctl", line 11, in <module>
    load_entry_point('registries-conf-ctl==1.0', 'console_scripts', 'registries-conf-ctl')()
  File "/usr/local/lib/python3.6/site-packages/registries_conf_ctl/cli.py", line 183, in main
    'Failed to read any file')
  File "/usr/local/lib/python3.6/site-packages/registries_conf_ctl/cli.py", line 144, in _raise_if_all_fail
    raise ValueError('{what}: {e}'.format(what=what,e=e))
ValueError: Failed to read any file: Failed to read /etc/containers/registries.conf: unknown file. maybe empty?
```

**Comment by liewegas** [comment]
Hmm.  Now that our throttle is removed an easy workaround is to just turn the mirror off?

**Comment by liewegas** [comment]
I'm getting a different error:
```
Error: error creating build container: Error initializing source docker://docker-mirror.front.sepia.ceph.com:5000/library/centos:8: error pinging docker registry docker-mirror.front.sepia.ceph.com:5000: Get https://docker-mirror.front.sepia.ceph.com:5000/v2/: x509: certificate signed by unknown authority
```
see https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/50366//consoleFull

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-01-20_09:35:12-rados:cephadm-wip-swagner-testing-2021-01-19-1509-distro-basic-smithi/5804847

**Comment by djgalloway** [comment]
> I'm getting a different error:
> 
> ```
> Error: error creating build container: Error initializing source docker://docker-mirror.front.sepia.ceph.com:5000/library/centos:8: error pinging docker registry docker-mirror.front.sepia.ceph.com:5000: Get https://docker-mirror.front.sepia.ceph.com:5000/v2/: x509: certificate signed by unknown authority
> ```
> 
> see https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/50366//consoleFull

That's not related

**Comment by djgalloway** [comment]
> That's not related. I need to update the certificate on the Jenkins builders but my ansible to do that is failing because `registries-conf-ctl` is failing.

Maybe not.  Looking.

**Comment by djgalloway** [comment]
Okay, I think I have this fixed on testnodes (smithi/gibba). @sebastian-philipp I still need `registries-conf-ctl` fixed so the Jenkins builders (braggi) will use the mirror.

**Comment by sebastian-philipp** [comment]
fixed
